version: '3.8'
services:
  vector-agent:
    image: timberio/vector:0.39.0-debian
    container_name: vector-agent
    volumes:
      - ~/Documents/vector_git/vector/agent/:/etc/vector/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TZ=Asia/Seoul
    